---
title: "0.0 - Introduction"
author: 
date: 
output: github_document
---

There are several locations in Bath where nitrogen dioxide (NO2) levels exceed legal limits. In 2017, the government directed Bath and North East Somerset Council (B&NES) to reduce levels of NO2 in the city.

Bath’s 2020 approved Class C Clean Air Zone (CAZ) was originally scheduled for introduction on November 4th 2020. However, due to the COVID-19 pandemic, the Government asked for the introduction of the CAZ to be postponed until January 2021 at the earliest, with a new date still to be agreed. The current policy will introduce daily charges for vehicles entering the CAZ as follows:

- Charges will only apply to higher emission; taxis, private hire vehicles (PHVs), light goods vehicles (LGVs), vans (including pick-ups and camper-vans), buses, coaches, and heavy goods vehicles (HGVs). 
- Vehicles in any of the following categories are exempt of charges; Euro 6 (or newer) diesel vehicles, Euro 4 (or newer) petrol vehicles, electric vehicles, hybrid vehicles, and alternatively fuelled vehicles. 
- For non-compliant vehicles, charges will be £100 a day for buses, HGVs and coaches and £9 a day for PHVs, vans (including pick-ups and camper-vans), minibuses, and LGVs. 
- Private cars and motorbikes will not be charged, regardless of their emission standards, which has sparked some controversy.

More information regarding the CAZ policy can be found on the Bath and North East Somerset council (B&NES) website. [1]

An independent review into Bath’s Class C CAZ has stated that it is ‘uncertain’ if the measures would deliver any tangible air quality improvements, and has recommended the authority draws up a contingency plan to reduce NO2 emissions. [2] 

A Class D CAZ which had been put out for consultation, would have charged all higher emission vehicles, including cars.

For two weeks in 2017, B&NES installed a network of 66 automatic number-plate recognition (ANPR) cameras which recorded passing vehicles in both directions at 33 sites around Bath. The recorded number plates were then matched with the Driver and Vehicle Licensing Agency (DVLA) database to determine information about each vehicle observed.

Using the ANPR data, this study will analyse the nature of traffic flows through London Road and congestion between London Road and the busiest routes that vehicles take, and their effect on NO2 pollution levels in Bath. Out of the 33 ANPR sites, London Road has been chosen to focus much of the analysis and modelling on, since there are two ANPR camera’s capturing traffic travelling inbound (towards the city centre) and outbound (away from the city centre), within close proximity to the London Road Automatic Urban and Rural Network (AURN) and London Road Enclosure air pollution monitoring stations (see the interactive map in section 0.2).




[1] Further information regarding the CAZ policy can be found [here](https://www.bathnes.gov.uk/bath-breathes-2021-overview).

[2] The independent review is available [here](https://democracy.bathnes.gov.uk/documents/s58248/E3152z Appendix 2 - Peer Review Report Aug19.pdf).


