---
title: "0.1 - Data information"
author: 
date: 
output: github_document
---
##0.1.1 - Raw data sources:

This project will be using raw data from the following sources:

- Traffic data from the B&NES 2017 ANPR survey: http://bit.ly/banesanprdata
- Air pollution data from: https://data.bathhacked.org/datasets/live-air-quality-sensor-data/download-csv
- Air pollution data for 2020 from: https://uk-air.defra.gov.uk/data_files/site_data/BHA4_2020.csv
- Weather data from : https://www.paulwilman.com

The raw files for the traffic data and air pollution data can be viewed in the folder **0.1.1 - Raw Data**.

##0.1.2 - Cleaned data files:

In the folder **0.1.2 - Data**, there are the following data sets (extracted from the raw data using the files **air_data_files.rmd**, **anpr_data_files.rmd** & **weather rda file**):

#### air.entire.rda 

This is a data frame of air pollution observations from 8th July 2014 - 5th May 2019, of the following 8 variables:

- **DateTime** the UTC timestamp of the observation.
- **Sensor Location Name** the name of the sensor site e.g. London Road AURN.
- **Sensor Location** the location of the sensor (WGS84 latitude, WGS84 longitude).
- **NO** the nitrogen oxide reading in parts per billion (ppb).
- **NO2** the nitrogen dioxide reading in ppb.
- **NOx** total of NO2 and NO.
- **CO** the carbon oxide reading in ppm.
- **PM10** the particulate matter 10 micrometres or less in diameter reading, measured in micrograms per cubic metre (µg/m3).

There are four air pollution monitoring stations:

- **London Road AURN** measuring NOx, NO & NO2 levels every 15 minutes.
- **Bath Guildhall** measuring NOx, NO & NO2 levels every 15 minutes.
- **London Road Enclosure** measuring NOx, NO, NO2 & PM10 levels hourly.
- **Windsor Bridge** measuring NOx, NO, NO2 & PM10 levels hourly.

The locations of these stations are shown on the interactive map in section 0.2.

#### air.data.rda 

This is **air.entire.rda** filtered to the 2017 ANPR survey period (31st October - 13th November).

#### vehicle.data.rda

This is a data frame giving information about the vehicles observed during 2017 ANPR survey, of the following 13 variables:

- **vehicles_id** the vehicle identifier (UUID to anonymise vehicles).
- **make** the make of vehicle e.g. Ford, Ferrari.
- **type** the type of vehicle e.g. CARS, PSVs.
- **subtype** the subtype of vehicle e.g. Moped.
- **intro_date** the date the vehicle was introduced.
- **euro_status** the Euro emission standard of the vehicle.
- **engine_capacity** the engine capacity in cm3.
- **gross_vehicle_weight** the gross vehicle weight in kg.
- **fuel_type the fuel type** e.g. Diesel, Petrol.
- **co2** carbon dioxide emissions in g/km.
- **fc_combined**  the fuel consumption across combined conditions in L/100km.
- **fc_extra_urban** the fuel consumption outside urban area in L/100km.
- **fc_urban_cold** the fuel consumption from cold start within urban area in L/100km.

The vehicle make may be suppressed where 5 or less vehicles of that make were observed. Some data values may be null where information is not available for a vehicle.

#### obs.data.rda

This is a data frame of vehicle observations from the 2017 survey, of the following 3 variables:

- **t** the UTC timestamp of the observation.
- **site_id** the ANPR camera of the observation.
- **vehicle_id** the vehicle identifier (UUID to anonymise vehicles). 

####site.data.rda

This is a data frame of 2017 ANPR survey site information of the following 10 variables:

- **site_id** the ANPR camera id.
- **name** the ANPR camera name.
- **description** the description of the ANPR site location.
- **location_id** the ANPR site location id e.g. 14 is the London Road ANPR site.
- **direction** the direction of travel e.g. E, W.
- **radial_group** the location relative to city centre; 1 = outer ring, 2 = inner ring, 3 = city centre car park, 4 = unclassified.
- **in_out** the direction towards city centre or entry/exit for car park; 1 = inbound/entry, 2 = outbound/exit.
- **longitude** WGS84 longitude.
- **latitude** WGS84 latitude.

There are 33 ANPR sites in total.

####weather.data.rda

This is a data frame of weather observations measured over the 2017 ANPR survey period (31st October-13th November), of the following 13 variables:

- **Time** the UTC timestamp of the observation.
- **TemperatureC** the air temperature in degrees Celsius.
- **DewpointC** the dew point in degrees Celsius.
- **PressurehPa** the pressure in hectopascals (hPa).
- **WindDirection** the categorical wind direction e.g. SW.
- **WindDirectionDegrees** the wind direction in compass degrees e.g. 227.
- **WindSpeedKMH** the wind speed in kilometres per hour.
- **WindSpeedGust** the wind speed gust in kilometres per hour.
- **Humidity** the humidity percentage.
- **HourlyPrecipMM** the hourly amount of precipitation in mm.
- **Conditions** the categorical weather conditions e.g. 'OVC' for overcast.
- **dailyrainMM** the daily amount of precipitation in mm.
- **SolarRadiationWatts/m^2** the solar radiation measured in watts per square metre (W/m2).